Verify it's not a kernel thread; plus, correct # VMAs
Signed-off-by: Kaiwan N Billimoria <kaiwan.billimoria@gmail.com>

diff --git a/vasu_grapher b/vasu_grapher
--- a/vasu_grapher
+++ b/vasu_grapher
@@ -1,7 +1,8 @@
 #!/bin/bash
-# vasu_graph
-# A simple Virtual Address Space - Usermode - Graphing (uvas_graph)
+# vasu_grapher
+# A simple Virtual Address Space - Usermode - Graphing
 # visualization utility
+# https://github.com/kaiwan/vasu_grapher.git
 name=$(basename $0)
 
 logfile_post_process()
@@ -29,6 +30,11 @@ PFX=$(dirname $(which $0))    # dir in which 'vasu_grapher' and tools reside
 # Check for process existence
 sudo kill -0 $1 >/dev/null 2>&1 || {
  echo "${name}: PID \"$1\" invalid (or dead now?) Aborting..."
+ exit 1
+}
+# Verify it's not a kernel thread
+sudo readlink /proc/$1/exe >/dev/null || {
+ echo "${name}: PID \"$1\" invalid; we believe it's a kernel thread. Aborting..."
  exit 1
 }
 
